/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai.quod.challenge;

import org.junit.Test;
import static org.junit.Assert.*;

public class HealthScoreCalculatorTest {
    @Test public void testAppHasAGreeting() {
        // HealthScoreCalculator classUnderTest = new HealthScoreCalculator();
        assertTrue("app should generate a csv", true);
    }
}
